### ISSUE TITLE
How Can I add other channels with different emojis with the same token?

### ISSUE THREAD

**Issue by karimawii** [woosal1337/AutoReaction-BOT#1]
How Can I add other channels with different emojis with the same token?

I want the bot to react to messages from another channel along with the first channel with different emojis, How can I do that?

**Comment by woosal1337** [comment]
You can add as many channels as you want by copying the Channel IDs, and pasting in the list of the Channel IDs, for instance:

```
emojis = [":whitemehaha:791189662055137281", ":kodluyoruz1:791195202748022784", ":kodluyoruz2:791195244662095872"]
channel_ids = [123456789, 987654321, 657385764]

if message.chanel.id in channel_ids:
  for i in emojis:
    await message.add_reaction(i)
```
